server:
  port: 1111

spring:
  application:
    name: reactive-demo-eureka


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/